theme: jekyll-theme-merlot
title: Lapsed Physicist ML Socials
description: "Lapsed (aka. Former) Physicists are plentiful in the machine learning community these sociaks are an informal opportunity to connect with members of the community."
