theme: jekyll-theme-merlot
title: [Lapsed Physicist ML Socials]
description: ['Lapsed' (aka. Former) Physicists are plentiful in the machine learning community. Inspired by Wine and Cheese seminars at many institutions, this BYOWC (Bring Your Own Wine and Cheese) event is an informal opportunity to connect with members of the community.]
